#!/usr/bin/python3


raw = '''g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp.
bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle
qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj.'''

# print(raw)
# ~                     
text = 'map'
table = str.maketrans(
	'abcdefghijklmnopqrstuvwxyz', 
	'cdefghijklmnopqrstuvwxyzab' 
	) 

res=(raw.translate(table))

print(text.translate(table))


# map.translate(res)
# map.translate()
# print(res)


/ocr 
